name: nexthack
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  speech_to_text: ^6.6.2
  camera: ^0.10.5+9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/background.jpeg
    - assets/genderpage.jpg
    - assets/images.png
    - assets/Image_0.png
    - assets/Image_1.png
    - assets/Image_2.png
    - assets/Image_3.png

  fonts:
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
